function(set_speed_optimization target build_type)
  if(build_type STREQUAL "Release")
    if (UNIX AND NOT APPLE)
      if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${target} PRIVATE -O3)
      endif()
    elseif (MSVC)
      target_compile_options(${target} PRIVATE /O2)
    endif()
  endif()
endfunction()