function(set_warning_flags target build_type)
  if(build_type STREQUAL "Debug")
    if (UNIX AND NOT APPLE)
      if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${target} PRIVATE -Wall -Wextra)
      endif()
    elseif (MSVC)
      target_compile_options(${target} PRIVATE /W4)
    endif()
  endif()
endfunction()